<?php include 'layout/head.php'; ?>
<?php
	if (empty($_SERVER['HTTPS']) || $_SERVER['HTTPS'] === "off") {
		$location = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
		header('HTTP/1.1 301 Moved Permanently');
		header('Location: ' . $location);
		exit;
	}
?>
<?php include 'layout/header-eng.php'; ?>
  <main class="o-main | js-main">
    <section id="h-1" class="o-layout show-me | js-hero">
      <div class="c-hero" style="position: relative; overflow: hidden;">
        <div class="growSc"></div>
        <div class="c-hero__container">
          <h1 class="c-hero__title pb50">
            <span class="enter-y delay-1" style="display: block;">We know how to do it,</span>
            <span class="enter-y delay-2" style="display: block;">sensationally.</span>
          </h1>
          <div class="enter-y delay-3">
            <div class="c-hero__text nav__item__mobile" data-anchor="about">See more</div>
          </div>
        </div>
      </div>
    </section>
    <section id="h-2" class="o-layout show-me | js-about" data-offset="-200">
      <div class="c-concept">
        <div class="c-concept__container--1">
          <h2 class="c-concept__title">
            <span class="enter-y delay-2" style="display: block;">WE COME TO</span>
            <span class="enter-y delay-3" style="display: block;">REVOLUTIONIZE</span>
            <small class="enter-y delay-4 small" style="display: block;">by introducing a</small>
            <small class="enter-y delay-5 small" style="display: block;">new concept of plant-based foods</small>
          </h2>
        </div>
        <div class="c-concept__container--2 innovate-img">
        </div>
        <div class="rueda_ergo" style="z-index: 10;">
          <img class="rueda" src="./assets/images/rueda.png" alt="">
        </div>
      </div>
    </section>
    <section id="h-2" class="o-layout show-me | js-about" data-offset="-200">
      <div class="c-concept">
	    <div class="c-concept__container--1 mission-img">
        </div>
        <div class="c-concept__container--2 o-orange">
          <p class="pb20 enter-y delay-2">
            ERGO Bioscience is an Argentinian biotech start-up, that <br>
            has achieved a deeper understanding of those <br>
            combinations that allow us to create and <br>
            reproduce organoleptically identical products <br>
            to those derived from animals, in order to <br>
            create unique, healthy and sustainable <br>
            gastronomic experiences.
          </p>
          <p class="we-mi enter-y delay-3">We have a mission:</p>
          <p class="enter-y delay-4">
            Reinvent and revolutionize the food industry, by <br>
            offering the most innovative and sustainable <br>
            solutions, in conjunction with science and nature.
          </p>
        </div>
      </div>
    </section>
    <section class="o-layout show-me | js-about" data-offset="-200">
      <div class="c-concept">
        <div class="c-concept__container--2 band-img">
        </div>
      </div>
    </section>
    <section id="h-17" class="o-layout show-me" data-offset="-250">
      <div class="c-hero" style="position: relative; overflow: hidden;">
        <div class="enter-sc" style="position: absolute; top:0; left: 0; width: 100%; height: 100%;background: url('./assets/images/hero.jpg'); background-size: cover !important; background-repeat: no-repeat !important; background-position: left center !important;"></div>
        <div class="c-hero__container">
          <h1 class="c-hero__title pb50">
            <span class="enter-y delay-1" style="display: block;">Four steps</span>
            <span class="enter-y delay-2" style="display: block;">that differentiate us</span>
          </h1>
          <div class="enter-y delay-3">
            <div class="c-hero__text nav__item__mobile" data-anchor="steps">Learn more</div>
          </div>
        </div>
      </div>
    </section>
    <section id="h-3" class="o-layout show-me pt200 | js-steps" data-offset="-200">
      <div class="paso-1">
        <!-- <div class="paso-1-title">1</div> -->
        <div class="paso-1-con">
          <div class="paso-1-ww">
            <h4 class="enter-y delay-2">STEP ONE</h4>
            <h3 class="h-t-p enter-y delay-3">Let's start with a question:</h3>
            <h2 class="enter-y delay-4">What defines the taste of food?</h2>
            <h3 class="h-t-pp enter-y delay-5">We identify the proteins of interest</h3>
            <div class="paso-1-img enter-y delay-6">
              <img src="./assets/images/ilus/paso1.png" alt="Identificacioón de proteinas Target">
            </div>
          </div>
          <div class="paso-1-ww ps1ww">
            <p class="paso-1-text enter-y delay-4">
              We know that taste and smell is defined by molecules generated by <br>
              chemical reactions prior or during cooking. The Ergo process begins <br>
              with the identification of those key proteins present in the generation <br>
              of those characteristic flavors and smell of animal foods: <strong class="gr-t">Myoglobin and Casein.</strong> <br> <br> 
              <strong class="gr-t">Myoglobin</strong> is the protein that gives red coloration to beef and participates <br>
              in the formation of the flavor and smell that we associate with roast beef. <br> <br> 
              <strong class="gr-t">Casein</strong> are a family of proteins present in milk and play a fundamental <br> 
              role in the texture and flavors of fermented dairy products such as cheese and yogurt. <br> 
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="o-layout pt200">
      <div class="paso-1">
        <!-- <div class="paso-1-title">1</div> -->
        <div id="h-4" class="paso-1-con show-me pb100" data-offset="-200">
          <div class="paso-1-ww">
            <h4 class="mb10 enter-y delay-2">STEP TWO</h4>
            <h2 class="mb20 enter-y delay-3">
              What do we do with these <br>
              proteins and how we produce <br>
              food without using animals?
            </h2>
            <h5 class="mb50 enter-y delay-4">
              Carrots! Protagonists par excellence
            </h5>
            <p class="paso-1-text enter-y delay-5">
              Over the last few years biotechnology has evolved to an exponential, <br>
              so the access for totally safe tools and resources nowadays, allow us to <br>
              use plant cells to produce those proteins of interest. The team of Ergo <br>
              scientists has developed an innovative method, by using carrot cells. <br>
              They are not only able to express <strong class="gr-t">myoglobin and casein</strong> exceptionally <br>
              (similar as we find it in beef and dairy derivatives) but also give us a <br>
              plus of important nutrients, such as beta - carotene.
            </p>
          </div>
          <div class="paso-2-ww">
            <div class="paso-2-img enter-y delay-4">
              <img src="./assets/images/ilus/paso3.png" alt="Desarrollo de Células">
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="h-33" class="o-layout show-me pt100" data-offset="-200">
      <div class="paso-1">
        <div class="paso-1-con">
          <div class="paso-1-ww">
            <h4 class="enter-y delay-2">STEP THREE</h4>
            <h2 class="enter-y delay-3">
              And... Is this <br> process sustainable? <br>
            </h2>
            <h3 class="h-t-pp enter-y delay-4">We transform cells and produce on a large scale</h3>
            <div class="paso-1-img enter-y delay-5">
              <img class="imagenTres" src="./assets/images/ilus/paso2.png" alt="Identificacioón de proteinas Target">
            </div>
          </div>
          <div class="paso-1-ww pasd3WW">
            <p class="paso-1-text enter-y delay-4">
              To produce plant foods from <strong class="gr-t">myoglobin or caseins</strong>, we need to obtain them on a large scale. For this we develop a platform known as Plant Cell Suspension Culture (PCSC). This platform allows us to introduce small amounts of the cells into bioreactors and induce their reproduction under controlled conditions until we obtain industrial quantities, which later are purified under the most rigorous standards. All this, without animals, excessive water use and harmful greenhouse gas emissions.
            </p>
          </div>
        </div>
      </div>
    </section>
    <section id="h-6" class="o-layout show-me pt200" data-offset="-200">
      <div class="paso-1">
        <!-- <div class="paso-1-title">1</div> -->
        <div class="paso-2-m pb80">
          <div class="paso-2-mw to-l">
            <h4 class="mb10 enter-y delay-2">STEP FOUR</h4>
            <h2 class="mb40 enter-y delay-3">
              We formulate a nutritious <br>
              mix to create delicious <br>
              Plant - based foods
            </h2>
            <p class="paso-1-text enter-y delay-4">
              The proteins obtained in quantity, are incorporated into a mix <br>
              of other Plant - based ingredients such as soy proteins, pea <br>
              proteins, coconut oil, vegetable fibers and others .This is how <br>
              we create delicious products with an indistinguishable flavor and <br>
              extraordinarily similar to animal derivatives, without resorting <br>
              to them and of course in an ultra - sustainable way
            </p>
          </div>

          <div class="paso-2-mw enter-y delay-5">
            <img class="tss" src="./assets/images/ilus/paso4.png" alt="">
          </div>
        </div>
      </div>
    </section>
    <section id="h-7" class="o-layout show-me pt100 | js-team" data-offset="-200">
      <div class="team pb100">
        <h2 class="team__title enter-x-r delay-1">OUR TEAM</h2>
        <div class="team__cc mb100">
          <div class="team_w enter-x-r delay-2">
            <img class="mr50" src="./assets/images/team/Ale Barbarini.jpg" alt="">
          </div>
          <div class="team_w" style="margin-left: -10rem;">
            <h4 class="team_name mb10 enter-y delay-3">Alejandro Barbarini</h4>
            <p class="team_puesto mb20 enter-y delay-4">CEO</p>
            <p class="team_t mb50 enter-y delay-5">
              A passionate biotechnologist graduated from the Faculty of Biochemistry and <br>
              Sciences Biologics of the UNL (Argentina) in 2009. In 2010, he began his <br>
              studies of PhD in Chemistry, with a focus on the development of <br>
              nanoparticles for contracted release of anticancer drugs. Alejandro is <br>
              the author of two scientific publications in journals and two international <br>
              patents. Recently distinguished by the MIT Technology Review as one of the <br>
              young innovators under 35 for Latin America.
            </p>
            <div class="enter-y delay-7">
              <a href="#" class="team-link">WATCH PROFILE</a>
            </div>
          </div>
        </div>
        <div class="team__cc rev">
          <div class="team_w" style="align-items: flex-start;">
            <h4 class="team_name mb10 enter-y delay-2">Maria Laura García</h4>
            <p class="team_puesto mb20 enter-y delay-3">SCIENTIFIC DIRECTOR</p>
            <p class="team_t mb50 enter-y delay-4">
              Biochemist and Doctor in Biological Sciences. She is currently a Researcher <br>
              Principal of CONICET and directs the Plant Biotechnology and Virology group<br>
              of the Institute of Biotechnology and Molecular Biology of the Department<br>
              of Sciences Exact from UNLP (Argentina). His doctoral work focused on studying<br>
              of the replication mechanisms of RNA 1 and 2 of the Mosaic Virus "Alfalfa"<br>
              carried out by the Department of Biochemistry of the University of Leiden of the<br>
              Netherlands. Throughout her career as a researcher, she has achieved 40<br>
              publications in international magazines, she is the author of 7 book chapters and<br>
              she was director of 9 doctoral theses. His technical expertise focuses on the<br>
              plant biotechnology and molecular biology.
            </p>
            <div class="enter-y delay-7">
              <a href="#" class="team-link">WATCH PROFILE</a>
            </div>
          </div>
          <div class="team_w enter-x delay-7" style="margin-left: -10rem;">
            <img class="ml50" src="./assets/images/team/Maria Laura Garcia.jpg" alt="">
          </div>
        </div>
      </div>
      <div class="team pb100">
        <h2 class="team__title enter-x-r delay-1">Our Team</h2>
        <div class="team__cc mb100">
          <div class="team_w enter-x-r delay-2">
            <img class="mr50" src="./assets/images/team/Eduardo Peña.jpg" alt="">
          </div>
          <div class="team_w" style="margin-left: -10rem;">
            <h4 class="team_name mb10 enter-y delay-3">Eduardo Peña</h4>
            <p class="team_puesto mb20 enter-y delay-4">CSO</p>
            <p class="team_t mb50 enter-y delay-5">
              Biotechnologist and Doctor in Biological Sciences, he is currently <br>
              CONICET Adjunct Researcher and member of the<br>
              Biotechnology and Plant Virology from the Institute of Biotechnology<br>
              and Molecular Biology from the Faculty of Exact Sciences (UNLP).<br>
              He completed his postdoctoral fellowship at the Institute of Plant Biology<br>
              Molecular de in Strasbourg (France). Throughout his career<br>
              as a researcher he has achieved 21 publications in journals<br>
              international. He is also the author of four book chapters.<br>
              His technical experience focuses on plant biotechnology and<br>
              molecular biology
            </p>

            <div class="enter-y delay-7">
              <a href="#" class="team-link">WATCH PROFILE</a>
            </div>

          </div>

        </div>

        <div class="team__cc rev">

          <div class="team_w" style="align-items: flex-start;">

            <h4 class="team_name mb10 enter-y delay-2">Augusto Desuque</h4>
            <p class="team_puesto mb20 enter-y delay-3">CTO</p>

            <p class="team_t mb50 enter-y delay-4">
              Food Engineer from the Faculty of Chemistry of the UNL specialized <br>
              in Biotechnological Process Engineering at the CPE School in Lyon (France).<br>
              With a previous professional practice carried out at Sartorius-Stedim Biotech,<br>
              Aubagne (France), currently leads the development of food prototypes<br>
              plant-based at Ergo Biosciences.
            </p>

            <div class="enter-y delay-7">
              <a href="#" class="team-link">WATCH PROFILE</a>
            </div>

          </div>

          <div class="team_w enter-x delay-7" style="margin-left: -10rem;">
            <img class="ml50" src="./assets/images/team/Augusto Desuque.jpg" alt="">
          </div>

        </div>

      </div>

      <div class="team-add">

        <div class="team-w-add m7" style="border: 2px solid #fff;padding: 30px; border-radius: 25px;">
          <h4 class="team-ab-name mb20 enter-y delay-2">ADVISORY BOARD</h4>
          <p class="team-ab-p enter-y delay-3">
            In addition, our team includes scientists, experts in the food industry and business with decades of experience providing advice, contacts and ideas on a day-to-day basis to our projects.
          </p>
        </div>

        <div class="team-w-add">
          <h4 class="team-a-name m10 enter-y delay-2">Maria Stathi</h4>
          <p class="team-a-puesto mb20 enter-y delay-3">MARKETING AND MARKET ANALYSIS</p>
          <p class="team-a-p enter-y delay-4">
            María has a degree in Business Administration from the University of Thessaloniki (Greece)
            with two Master's degrees: in Finance from Brunel University (London); in Sales and Marketing by
            the IE School of Business (Madrid). For five years she was the sole VP assistant at Kimberly Clark
            for the European Union. His main responsibilities at KC include: Management
            of Marketing, the analysis of demand flows and the effective management of a
            $ 2 Billion dollars; add value by identifying innovation to different
            brands, among others.
          </p>
        </div>

      </div>

      <div class="team-add">

        <div class="team-w-add p7">
          <h4 class="team-a-name m10 enter-y delay-2">Markus Sack</h4>
          <p class="team-a-puesto mb20 enter-y delay-3">PLANT BIOTECHNOLOGY AND CELL CROPS</p>
          <p class="team-a-p enter-y delay-4">
            Markus obtained his Bachelor's and Doctorate in Biological Sciences from RWTH Aachen University (Germany). For almost two decades he has participated in research projects related to plant molecular culture and antibody engineering. In addition, he is a recognized SPR specialist and has carried out more than 150 projects that include all types of protein interaction tests, from small low-affinity molecules to high-affinity antibodies, viral particles and bio-nanomaterials, etc. He is the author of more than 50 scientific publications, co-inventor of 9 patents, and holds the rights to a PCT patent application for "Improved Genome Editing in Plants".
          </p>
        </div>

        <div class="team-w-add">
          <h4 class="team-a-name m10 enter-y delay-2">Gabriel Raya Tonetti</h4>
          <p class="team-a-puesto mb20 enter-y delay-3">TECHNOLOGY AND FOOD INDUSTRY</p>
          <p class="team-a-p enter-y delay-4">
            Gabriel is a Chemical Engineer graduated from the National University of Tucumán (Argentina) and a PhD in Chemical Engineering. He has a Doctorate and PhD in Management Development from the Universidad Católica Argentina. For more than 10 years he served as Innovation Manager and CTO at Grupo Arcor, the largest food company in Latin America. He currently holds the position of Secretary of Scientific-Technological Articulation in the Province of Córdoba (Argentina). In addition, he has done teaching work for undergraduate and graduate courses in different Argentine universities and is the author of various scientific publications and book chapters.
          </p>
        </div>

      </div>

      <div class="team-add pb50">

        <div class="team-w-add p7">
          <h4 class="team-a-name m10 enter-y delay-2">Cesar Vega</h4>
          <p class="team-a-puesto mb20 enter-y delay-3">TECHNOLOGY AND FOOD INDUSTRY</p>
          <p class="team-a-p enter-y delay-4">
            Cesar holds an MA and Ph.D. in Food Sciences from the University of Guelph and University College Cork, Ireland, respectively. In addition, his passion for food science has led him to obtain a culinary degree from Le Cordon Bleu (Canada) and then to edit the book "Kitchen as a Laboratory: Reflections on the science of food and cooking" (Columbia University Press, 2012). He has also served as the Innovation Leader at Mars Foods Europe in the Netherlands for over twelve years. Cesar was a critical reference in modernist cuisine at Myrhvold, a member of the editorial board of the International Journal of Food Gastronomy and Science "Elsevier" and Food Biophysics "Springer". Currently, he is in charge of the Global R&D Directorate for Barry Callebaut, Chicago (USA).
          </p>
        </div>

        <div class="team-w-add">
          <h4 class="team-a-name m10 enter-y delay-2">Nuno Anjo Silva</h4>
          <p class="team-a-puesto mb20 enter-y delay-3">BUSINESS MANAGEMENT AND STRATEGY</p>
          <p class="team-a-p enter-y delay-4">
            Nuno has a Master's Degree in Business Administration from the Catholic University of Portugal. With a long history
            in the corporate world, specifically in the management of business units related to food, has
            worked for 27 years for Unilever Europe, managing business units in different regions such as Lisbon,
            Brussels and Istanbul. In 2016, he was appointed as Out-Of-Home Channel Director at Unilever Europe. Actually
            is a business and financial advisor to several renowned companies
          </p>
        </div>

      </div>
    </section>
    <section id="h-8" class="o-layout show-me" style="position: relative;" data-offset="-200">
        <div class="slide">
          <div class="pre_c" style="overflow: hidden;">
          </div>
          <h2 class="pre-t">
            <div class="slideTitle">
              <span>Sustainability in the smartest way</span>
            </div>
          </h2>
        </div>
    </section>
    <section id="h-20" class="pb200 show-me" data-offset="-200">
      <div class=app-layout>
        <h1 class="enErgo pt80 mb80 enter-y delay-1">Promoting ecology and health are not only objectives</h1>
        <div class="app-grid mb50">
          <div class="app-grid-item enter-y delay-2">
            <div class="app-grid-vid">
              <video class="vid-app-g" loop muted autoplay src="./assets/images/Nube.mp4"></video>
            </div>
            <div class="app-grid-info">
              <h2 class="app-grid-t">
                Committed to 
                Reduce The co2 
                Footprint!
              </h2>
              <p class="app-grid-p"> 
                We create high protein foods from low energy biotechnological processes, without the need of resorting to animal husbandry. This implies almost zero emissions of greenhouse gas and energy consumption
              </p>
            </div>
          </div>
          <div class="app-grid-item enter-y delay-3">
            <div class="app-grid-vid">
              <video class="vid-app-g" loop muted autoplay src="./assets/images/Vaca.mp4"></video>
            </div>
            
            <div class="app-grid-info">
              <h2 class="app-grid-t">
              Protect  <br> 
              animals life
              </h2>
              <p class="app-grid-p">
                Ergo has develop a scalable process of myoglobin production without the use of animals
              </p>
            </div>
          </div>

          <div class="app-grid-item enter-y delay-4">
            <div class="app-grid-vid">
              <video class="vid-app-g" loop muted autoplay src="./assets/images/Gota.mp4"></video>
            </div>
            
            <div class="app-grid-info">
              <h2 class="app-grid-t">
                ReducIng Water <br>
                Consumption As <br>
                The lowest levels <br>
              </h2>
              <p class="app-grid-p">
                According to
                United
                Nation Water,
                the total
                water consumption for
                the manufacture of a
                100 grams burger is
                approximately 2400 Lt
                of water. A burger
                developed from our
                i
                ngredient would imply
                an average water
                consumption of
                approximately 1 Lt
                .
                A
                burger developed from
                our ingredient would
                have the protein and
                iron content of a
                traditional burger
              </p>
            </div>
          </div>

        </div>

        <div class="app-grid">

          <div class="app-grid-item enter-y delay-2">
            <div class="app-grid-vid">
              <video class="vid-app-g" loop muted autoplay src="./assets/images/Corazon.mp4"></video>
            </div>
            
            <div class="app-grid-info">
              <h2 class="app-grid-t">
                Contributing to <br>
                health and wellness
              </h2>
              <p class="app-grid-p">
                A Plant
                -
                based
                meat
                developed from our
                ingredient
                s
                not only
                would have the protein
                and iron content of a
                traditional burger
                , but
                also
                , it would
                be
                cholesterol free with no
                hormones or
                antibiotics
              </p>
            </div>
          </div>

          <div class="app-grid-item enter-y delay-3">
            <div class="app-grid-vid">
              <video class="vid-app-g" loop muted autoplay src="./assets/images/Burger.mp4"></video>
            </div>
            
            <div class="app-grid-info">
              <h2 class="app-grid-t">
                Providing <br>
                nutrition quality
              </h2>
              <p class="app-grid-p">
                Myoglobin provides the
                9 essential amino acids
                that our body does not
                synthesize. It would be
                the first
                Plant
                -
                based
                ingredient that is able to
                make this contribution.
                By expressing
                myoglobin in carrot
                cells, we make an
                important contribution
                of beta
                -
                carote
                ne and
                other
                Plant
                -
                based
                nutrients. We also
                provide heme iron, a
                form of iron that is more
                intestinally absorbed
                than mineral ir
                on
              </p>
            </div>
          </div>

        </div>

      </div>
    </section>

    <section id="h-9" class="o-layout show-me o-orange c-top | js-contact" style="position: relative;" data-offset="-200">
      <div class="c-wrap pt100 pb100">
        <div class="hola">
          <h2 class="block_service_title enter-y delay-3">Contact</h2>
          <p class="block_service_p enter-y delay-4">To learn more about this project send an email to:</p>
          <div class="mailA mailDiv enter-y delay-5">
            <form id="projectForm" method="post" class="form" data-scroll="fade">
              <div class="form__field pb30">
                <input type="text" name="name" placeholder="Name and Lastname">
              </div>
              <div class="form__field pb30">
                <input type="text" name="phone" placeholder="Phone">
              </div>
              <div class="form__field pb30">
                <input type="email" name="email" placeholder="Email">
              </div>
              <div class="form__field pb30">
                <textarea cols="30" name="message" rows="10" placeholder="Leave a message"></textarea>
              </div>
              <button id="btnF" class="about__content__btn">Send</button>
              <p class="sendit" style="opacity: 0; color: #000; line-height: 1.3;font-size: 16px;font-family:'ftregular';">Enviado</p>
            </form>
          </div>
        </div>
      </div>
    </section>

  </main>

  <div class="loader">
    <div class="loader-app">
      <svg class="loader-logo" style="width: 200px;" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 449.56 141.73" style="enable-background:new 0 0 449.56 141.73;" xml:space="preserve">
        <style type="text/css">
          .st0{fill:#69B976;}
          .st1{fill:#FFFFFF;}
          .st2{fill:#FFFFFF;stroke:#FFFFFF;stroke-width:0.75;stroke-miterlimit:10;}
        </style>
        <g>
          <g>
            <g>
              <g>
                <path class="st0" d="M154.89,36.76h16.52l-1.82,6.96h-14.7v11.1h19.72v7.35h-27.46V19.91h28.73l-1.88,7.13h-19.12V36.76z"/>
                <path class="st0" d="M181.8,30.85c0.63,0,1.16,0.22,1.6,0.66c0.44,0.44,0.66,0.98,0.66,1.6v0.22c1.03-0.88,2.17-1.58,3.43-2.07      c1.25-0.5,2.52-0.75,3.81-0.75c0.59,0,1.11,0.06,1.57,0.19c0.46,0.13,1,0.34,1.63,0.64v6.3c-1.36-0.22-2.58-0.33-3.65-0.33      c-2.54,0-4.31,0.64-5.3,1.91c-0.99,1.27-1.49,3.18-1.49,5.72v17.24h-7.24V30.85H181.8z"/>
                <path class="st0" d="M209.37,65.38c2.32,0,4.03-0.49,5.14-1.46c1.1-0.98,1.66-2.48,1.66-4.5v-0.72      c-1.99,1.66-4.38,2.49-7.18,2.49c-2.69,0-5.08-0.66-7.18-1.99c-2.1-1.33-3.74-3.17-4.92-5.53c-1.18-2.36-1.77-5.03-1.77-8.01      c0-2.98,0.58-5.65,1.74-8.01c1.16-2.36,2.77-4.19,4.83-5.5c2.06-1.31,4.4-1.96,7.02-1.96c2.98,0,5.49,0.81,7.51,2.43      c0.11-0.52,0.37-0.94,0.77-1.27c0.41-0.33,0.88-0.5,1.44-0.5h4.97v28.4c0,3.94-1.22,7-3.67,9.17      c-2.45,2.17-5.87,3.26-10.25,3.26c-3.76,0-6.8-0.73-9.12-2.18c-2.32-1.45-3.74-3.49-4.25-6.11h6.41c0.44,0,0.87,0.2,1.27,0.61      C204.75,64.92,206.61,65.38,209.37,65.38z M209.2,54.66c2.5,0,4.35-0.75,5.52-2.24c1.18-1.49,1.77-3.82,1.77-6.99      c0-2.95-0.61-5.14-1.82-6.57c-1.22-1.44-3.06-2.16-5.53-2.16c-2.14,0-3.78,0.77-4.94,2.32c-1.16,1.55-1.74,3.78-1.74,6.68      c0,2.87,0.59,5.08,1.77,6.63C205.41,53.89,207.07,54.66,209.2,54.66z"/>
                <path class="st0" d="M227.02,54.97c-1.31-2.49-1.96-5.29-1.96-8.42c0-3.13,0.65-5.94,1.96-8.43c1.31-2.49,3.11-4.44,5.41-5.86      c2.3-1.42,4.91-2.13,7.82-2.13c2.91,0,5.52,0.7,7.82,2.1c2.3,1.4,4.1,3.35,5.39,5.86c1.29,2.5,1.93,5.32,1.93,8.45      c0,3.13-0.64,5.95-1.93,8.45c-1.29,2.5-3.08,4.46-5.39,5.86c-2.3,1.4-4.91,2.1-7.82,2.1c-2.91,0-5.51-0.71-7.82-2.13      C230.13,59.4,228.33,57.45,227.02,54.97z M248.04,46.54c0-3.09-0.7-5.53-2.1-7.29c-1.4-1.77-3.3-2.65-5.69-2.65      c-2.39,0-4.3,0.88-5.72,2.65c-1.42,1.77-2.13,4.2-2.13,7.29c0,3.06,0.71,5.47,2.13,7.24c1.42,1.77,3.32,2.65,5.72,2.65      c2.39,0,4.29-0.87,5.69-2.62C247.34,52.06,248.04,49.63,248.04,46.54z"/>
                <path class="st1" d="M165.28,72.77c4.53,0,8.03,1.29,10.5,3.87c0.96,0.96,1.68,2.1,2.18,3.42c0.5,1.33,0.75,2.74,0.75,4.25      c0,3.65-1.44,6.39-4.31,8.23c1.88,0.96,3.33,2.28,4.36,3.98c1.03,1.69,1.55,3.63,1.55,5.8c0,1.62-0.29,3.17-0.86,4.64      c-0.57,1.47-1.37,2.76-2.4,3.87c-1.25,1.36-2.82,2.4-4.7,3.12c-1.88,0.72-3.94,1.08-6.19,1.08h-19V72.77H165.28z M169.34,88.35      c1.09-0.88,1.63-2.14,1.63-3.76c0-1.51-0.49-2.68-1.46-3.51c-0.98-0.83-2.37-1.24-4.17-1.24h-10.44v9.83h9.78      C166.7,89.67,168.25,89.23,169.34,88.35z M171.14,106.19c0.92-0.92,1.38-2.12,1.38-3.59c0-1.91-0.6-3.39-1.8-4.42      c-1.2-1.03-2.9-1.55-5.11-1.55h-10.72v11.16h11.05C168.34,107.79,170.07,107.26,171.14,106.19z"/>
                <path class="st1" d="M188.65,73.65c0.44,0.44,0.66,0.98,0.66,1.6V81h-1.44c-1.69,0-3.1-0.56-4.23-1.68      c-1.12-1.12-1.68-2.53-1.68-4.23v-2.1h5.08C187.67,72.99,188.21,73.21,188.65,73.65z M189.31,115.03h-7.24V83.71h7.24V115.03z"/>
                <path class="st1" d="M192.93,107.82c-1.31-2.49-1.96-5.29-1.96-8.42c0-3.13,0.65-5.94,1.96-8.43c1.31-2.49,3.11-4.44,5.41-5.86      c2.3-1.42,4.91-2.13,7.82-2.13c2.91,0,5.52,0.7,7.82,2.1c2.3,1.4,4.1,3.35,5.39,5.86c1.29,2.5,1.93,5.32,1.93,8.45      c0,3.13-0.64,5.95-1.93,8.45c-1.29,2.5-3.08,4.46-5.39,5.86c-2.3,1.4-4.91,2.1-7.82,2.1c-2.91,0-5.52-0.71-7.82-2.13      C196.04,112.26,194.24,110.31,192.93,107.82z M213.95,99.4c0-3.09-0.7-5.53-2.1-7.29c-1.4-1.77-3.3-2.65-5.69-2.65      c-2.39,0-4.3,0.88-5.72,2.65c-1.42,1.77-2.13,4.2-2.13,7.29c0,3.06,0.71,5.47,2.13,7.24c1.42,1.77,3.32,2.65,5.72,2.65      c2.39,0,4.29-0.87,5.69-2.62C213.25,104.91,213.95,102.49,213.95,99.4z"/>
                <path class="st1" d="M233.84,108.59c0.99,0.5,2.36,0.75,4.09,0.75c1.73,0,3.04-0.29,3.92-0.86c0.88-0.57,1.33-1.39,1.33-2.46      c0-0.7-0.16-1.25-0.47-1.66c-0.31-0.41-0.91-0.76-1.79-1.08c-0.88-0.31-2.25-0.67-4.09-1.08c-2.5-0.52-4.54-1.07-6.1-1.66      c-1.57-0.59-2.9-1.54-4.01-2.85c-1.1-1.31-1.66-3.1-1.66-5.39c0-2.87,1.04-5.13,3.12-6.77c2.08-1.64,4.93-2.46,8.54-2.46      c3.65,0,6.55,0.88,8.7,2.65c2.15,1.77,3.43,4.29,3.84,7.57l-7.35-0.22c-0.22-1.36-0.74-2.32-1.55-2.87      c-0.81-0.55-2.06-0.83-3.76-0.83c-1.44,0-2.52,0.23-3.26,0.69c-0.74,0.46-1.1,1.13-1.1,2.02c0,0.59,0.16,1.06,0.47,1.41      s0.92,0.66,1.82,0.94c0.9,0.28,2.33,0.6,4.28,0.97c2.47,0.52,4.49,1.1,6.08,1.74c1.58,0.64,2.91,1.65,3.98,3.01      c1.07,1.36,1.6,3.24,1.6,5.64c0,3.09-1.13,5.54-3.4,7.35c-2.27,1.8-5.35,2.71-9.25,2.71c-4.13,0-7.41-0.96-9.86-2.87      c-2.45-1.92-3.84-4.64-4.17-8.18h5.97c0.88,0,1.53,0.48,1.93,1.44C232.13,107.31,232.85,108.1,233.84,108.59z"/>
                <path class="st1" d="M253.54,107.82c-1.31-2.49-1.96-5.29-1.96-8.42c0-3.13,0.65-5.94,1.96-8.43c1.31-2.49,3.11-4.44,5.41-5.86      c2.3-1.42,4.91-2.13,7.82-2.13c3.94,0,7.15,1.14,9.64,3.42c2.49,2.28,3.86,5.38,4.12,9.28h-7.29c-0.11-2.03-0.73-3.57-1.85-4.64      c-1.12-1.07-2.66-1.6-4.61-1.6c-2.39,0-4.3,0.88-5.72,2.65c-1.42,1.77-2.13,4.2-2.13,7.29c0,3.06,0.71,5.47,2.13,7.24      c1.42,1.77,3.32,2.65,5.72,2.65c1.81,0,3.23-0.43,4.28-1.3c1.05-0.87,1.72-2.11,2.02-3.73c0.11-0.63,0.36-1.12,0.75-1.49      c0.39-0.37,0.87-0.55,1.46-0.55h5.14c-0.04,4.24-1.27,7.56-3.7,9.97s-5.75,3.62-9.94,3.62c-2.91,0-5.51-0.71-7.82-2.13      C256.65,112.26,254.85,110.31,253.54,107.82z"/>
                <path class="st1" d="M289.87,73.65c0.44,0.44,0.66,0.98,0.66,1.6V81h-1.44c-1.69,0-3.1-0.56-4.23-1.68s-1.68-2.53-1.68-4.23      v-2.1h5.08C288.89,72.99,289.43,73.21,289.87,73.65z M290.53,115.03h-7.24V83.71h7.24V115.03z"/>
                <path class="st1" d="M295.23,107.9c-1.29-2.5-1.93-5.34-1.93-8.51c0-3.09,0.64-5.89,1.93-8.4c1.29-2.5,3.08-4.47,5.36-5.88      c2.28-1.42,4.82-2.13,7.62-2.13c3.09,0,5.75,0.77,7.98,2.32c2.23,1.55,3.9,3.74,5.03,6.57c1.12,2.84,1.61,6.15,1.46,9.94h-21.88      c0.37,2.36,1.22,4.19,2.54,5.5c1.33,1.31,3.04,1.96,5.14,1.96c3.32,0,5.45-1.42,6.41-4.25c0.18-0.52,0.44-0.91,0.77-1.19      c0.33-0.28,0.74-0.41,1.22-0.41h5.53c-0.48,3.87-1.95,6.9-4.42,9.09c-2.47,2.19-5.63,3.29-9.5,3.29c-2.95,0-5.57-0.69-7.87-2.07      C298.31,112.35,296.52,110.41,295.23,107.9z M301.03,95.69h14.03c-0.33-2.1-1.08-3.69-2.24-4.78c-1.16-1.09-2.7-1.63-4.61-1.63      c-1.84,0-3.38,0.55-4.61,1.66C302.36,92.05,301.51,93.63,301.03,95.69z"/>
                <path class="st1" d="M330.48,83.71c0.55,0,1.04,0.17,1.46,0.53c0.42,0.35,0.67,0.8,0.75,1.35c2.14-1.69,4.75-2.54,7.84-2.54      c3.43,0,6.11,0.94,8.07,2.82s2.93,4.46,2.93,7.73v21.44h-7.24V93.98c0-1.44-0.43-2.53-1.3-3.29c-0.87-0.76-2.13-1.13-3.79-1.13      c-1.91,0-3.47,0.61-4.67,1.82c-1.2,1.22-1.8,2.78-1.8,4.7v18.95h-7.24V83.71H330.48z"/>
                <path class="st1" d="M356.64,107.82c-1.31-2.49-1.96-5.29-1.96-8.42c0-3.13,0.65-5.94,1.96-8.43c1.31-2.49,3.11-4.44,5.41-5.86      c2.3-1.42,4.91-2.13,7.82-2.13c3.94,0,7.15,1.14,9.64,3.42c2.49,2.28,3.86,5.38,4.12,9.28h-7.29c-0.11-2.03-0.73-3.57-1.85-4.64      c-1.12-1.07-2.66-1.6-4.61-1.6c-2.39,0-4.3,0.88-5.72,2.65c-1.42,1.77-2.13,4.2-2.13,7.29c0,3.06,0.71,5.47,2.13,7.24      c1.42,1.77,3.32,2.65,5.72,2.65c1.81,0,3.23-0.43,4.28-1.3c1.05-0.87,1.72-2.11,2.02-3.73c0.11-0.63,0.36-1.12,0.75-1.49      c0.39-0.37,0.87-0.55,1.46-0.55h5.14c-0.04,4.24-1.27,7.56-3.7,9.97s-5.75,3.62-9.94,3.62c-2.91,0-5.51-0.71-7.82-2.13      C359.75,112.26,357.94,110.31,356.64,107.82z"/>
                <path class="st1" d="M388.32,107.9c-1.29-2.5-1.93-5.34-1.93-8.51c0-3.09,0.64-5.89,1.93-8.4c1.29-2.5,3.08-4.47,5.36-5.88      c2.28-1.42,4.82-2.13,7.62-2.13c3.09,0,5.75,0.77,7.98,2.32c2.23,1.55,3.9,3.74,5.03,6.57c1.12,2.84,1.61,6.15,1.46,9.94H393.9      c0.37,2.36,1.22,4.19,2.54,5.5c1.33,1.31,3.04,1.96,5.14,1.96c3.32,0,5.45-1.42,6.41-4.25c0.18-0.52,0.44-0.91,0.77-1.19      c0.33-0.28,0.74-0.41,1.22-0.41h5.53c-0.48,3.87-1.95,6.9-4.42,9.09c-2.47,2.19-5.63,3.29-9.5,3.29c-2.95,0-5.57-0.69-7.87-2.07      C391.41,112.35,389.61,110.41,388.32,107.9z M394.12,95.69h14.03c-0.33-2.1-1.08-3.69-2.24-4.78c-1.16-1.09-2.7-1.63-4.61-1.63      c-1.84,0-3.38,0.55-4.61,1.66C395.46,92.05,394.6,93.63,394.12,95.69z"/>
                <path class="st1" d="M424.9,107.46c0.44,0.44,0.66,0.98,0.66,1.6v5.97h-2.21c-1.69,0-3.1-0.56-4.23-1.69      c-1.12-1.12-1.69-2.53-1.69-4.23v-2.32h5.86C423.92,106.8,424.46,107.02,424.9,107.46z"/>
              </g>
            </g>
            <g>
              <path class="st2" d="M429.86,74.51h-3.05v8.96h-0.2v-8.96h-3.05v-0.19h6.3V74.51z"/>
              <path class="st2" d="M440.77,74.32v9.15h-0.2v-8.9l-4.23,8.9h-0.27l-4.23-8.9v8.9h-0.2v-9.15h0.32l4.26,8.96l4.24-8.96H440.77z"/>
            </g>
          </g>
          <g>
            <g>
              <path class="st0" d="M62.42,75.21c2.55,2.55,3.82,5.63,3.82,9.23v34.39H53.5c-9.77,0-17.88-3.24-24.36-9.71     c-6.47-6.47-9.71-14.59-9.71-24.36V71.39h33.75C56.79,71.39,59.87,72.66,62.42,75.21z"/>
              <path class="st1" d="M62.42,23.12c2.55,2.55,3.82,5.63,3.82,9.23v34.39H53.5c-9.77,0-17.88-3.24-24.36-9.71     c-6.47-6.47-9.71-14.59-9.71-24.36V19.3h33.75C56.79,19.3,59.87,20.58,62.42,23.12z"/>
            </g>
            <g>
              <path class="st1" d="M85.16,71.39h33.75v13.37c0,9.76-3.24,17.88-9.71,24.36c-6.47,6.47-14.59,9.71-24.36,9.71H72.11V84.44     c0-3.61,1.27-6.69,3.82-9.23C78.48,72.66,81.56,71.39,85.16,71.39z"/>
              <path class="st1" d="M85.16,19.3h33.75v13.37c0,9.77-3.24,17.88-9.71,24.36c-6.47,6.47-14.59,9.71-24.36,9.71H72.11V32.36     c0-3.61,1.27-6.69,3.82-9.23C78.48,20.58,81.56,19.3,85.16,19.3z"/>
            </g>
          </g>
        </g>
      </svg>
    </div>
  </div>

<?php include 'layout/footer.php'; ?>